#ifndef PARAMETERS_H
#define PARAMETERS_H

#define DEFAULT_TICKINTERVAL 50

#define MISSILE_MAX_SPEED 0.05
#define MISSILE_START_ENERGY 1000
#define MINE_START_ENERGY 5000

#define ACCELERATION_COST 2
#define ACCELERATION_FORCE 0.001

#define MISSILE_COST 10
#define SEEKING_MISSILE_COST 15
#define MINE_COST 20

#define MISSILE_DAMAGE 50

#define ROTATE_COST 1
#define ROTATE_AMOUNT 10

#define START_ENERGY 1000

#define MAX_PLAYERS 4
#define MAX_ROUNDS 4

#endif // PARAMETERS_H
