#ifndef PARAMETERS_H
#define PARAMETERS_H

#define TICKLENGTH 50
#define TICKLENGTH_DEBUG 200

#define ACCELERATION_COST 10
#define ACCELERATION_FORCE 0.001

#define ROTATE_COST 1
#define ROTATE_AMOUNT 10

#define START_ENERGY 1000

#define MAX_PLAYERS 4
#define MAX_ROUNDS 4

#endif // PARAMETERS_H
