#ifndef PARAMETERS_H
#define PARAMETERS_H

#define DEFAULT_TICKINTERVAL 100

#define SUPERPELLET_DURATION 100

#define MAX_PLAYERS 4
#define MAX_ROUNDS 4

#define SUDDEN_DEATH_TIME 60

#endif // PARAMETERS_H
